# Generated by Django 3.0.7 on 2020-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(verbose_name='data ćwiczenia')),
                ('duration', models.PositiveIntegerField(verbose_name='czas trwania / liczba powtórzeń')),
                ('place', models.CharField(max_length=32, verbose_name='miejsce')),
                ('place_description', models.CharField(blank=True, max_length=128, verbose_name='opis miejsca')),
                ('description', models.TextField(verbose_name='opis ćwiczenia')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='zdjęcie')),
                ('film', models.URLField(blank=True, verbose_name='nagranie')),
                ('rating', models.SmallIntegerField(choices=[(-2, 'bardzo źle'), (-1, 'kiepsko'), (0, 'średnio'), (1, 'dobrze'), (2, 'bardzo dobrze')], default=0, verbose_name='ocenia zachowania psa')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
